dataset: "celeba"
subsample_train:
  0: 0.3
  2: 0.0
subsample_context:
  0: 0.7
  1: 0.4
  2: 0.2
  3: 1.0
enc_channels: 128
batch_size: 256
enc_levels: 5
init_channels: 32
lr: 3.e-4
epochs: 100
save_encodings: True